accounts/urls.py
from django.shortcuts import render
from django.urls import path

from . import views

urlpatterns = [
    path("login/", views.LoginUser.as_view(), name="login"),
    path("logout/", views.LogoutUser.as_view(), name="logout"),
    path("registration/", views.UserCreateView.as_view(), name="registration"),
    path("profile/", views.user_profile, name="profile"),
    path("show_receipt", views.show_receipt, name="show_receipt"),
]

foodplan/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render

from . import settings
from foodplanapp import views


urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "", render, kwargs={"template_name": "index.html"}, name="start_page"
    ),
    path(
        "food/", include("foodplanapp.urls")
    ), 
    path("user/", include("accounts.urls")),
    path("payment/", include("payments.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foodplanapp/models.py
from django.contrib.auth.models import User
from django.db import models

ORDER_DURATION = [(3, "3 мес"), (12, "12 мес")]
MENU_TYPE = [
    ("classic", "Классическое меню"),
    ("low_calorie", "Низкокалорийное меню"),
    ("vegan", "Вегетарианское меню"),
    ("keto", "Кето меню"),
]


class Price(models.Model):
    classic_menu = models.IntegerField("Классическое меню, руб/мес")
    low_calorie_menu = models.IntegerField("Низкокалорийное меню, руб/мес")
    vegan_menu = models.IntegerField("Вегетарианское меню, руб/мес")
    keto_menu = models.IntegerField("Кето меню, руб/мес")
    meal = models.IntegerField("Доплата за каждый прием пищи, руб")
    new_year_menu = models.IntegerField("Доплата за новогоднее меню, руб")
    allergy = models.IntegerField("Доплата за гипоаллергенное меню, руб")

    class Meta:
        verbose_name = "цена"
        verbose_name_plural = "цены"


class Order(models.Model):
    menu_type = models.CharField(
        "Тип меню", choices=MENU_TYPE, max_length=100, default="classic"
    )
    duration = models.IntegerField(
        "Срок подписки, мес", choices=ORDER_DURATION
    )
    breakfast = models.BooleanField("Завтраки")
    lunch = models.BooleanField("Обеды")
    dinner = models.BooleanField("Ужины")
    dessert = models.BooleanField("Десерты")
    new_year_menu = models.BooleanField("Новогоднее меню")
    persons_amount = models.IntegerField("Количество персон")
    allergies = models.ManyToManyField(
        "Allergies",
        related_name="orders",
    )
    promo_code = models.CharField(
        "Промокод",
        null=True,
        blank=True,
        max_length=20,
    )
    total_price = models.IntegerField("Стоимость подписки", null=True)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name="Пользователь"
    )

    class Meta:
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"

    def __str__(self):
        return f"Заказ №{self.id} для {self.user}"


class Allergies(models.Model):
    name = models.CharField(
        "Название",
        max_length=100,
    )
    description = models.TextField(
        "Описание",
        blank=True,
    )

    class Meta:
        verbose_name = "аллергия"
        verbose_name_plural = "аллергии"

    def __str__(self):
        return f"Аллергия на {self.name}"


class Dish(models.Model):
    name = models.CharField(
        "Название",
        max_length=200,
    )
    image = models.ImageField(
        "Изображение",
        upload_to="images/",
        null=True,
    )
    calories = models.FloatField(
        "Калорийность, ккал",
        blank=True,
        null=True,
    )
    weight = models.IntegerField(
        "Вес, г",
        blank=True,
        null=True,
    )
    guide = models.TextField(
        "Инструкция",
        blank=True,
    )
    active = models.BooleanField(
        "Активный",
        default=True,
    )
    menu_type = models.CharField(
        "Тип меню",
        choices=MENU_TYPE,
        max_length=100,
        default="classic",
        db_index=True,
    )
    allergies = models.ManyToManyField(
        "Allergies",
        related_name="dishes",
        blank=True,
    )

    class Meta:
        verbose_name = "рецепт"
        verbose_name_plural = "рецепты"

    def __str__(self):
        return self.name


class Dishitems(models.Model):
    dish = models.ForeignKey(
        "Dish",
        related_name="dishitems",
        on_delete=models.CASCADE,
        verbose_name="Рецепт",
    )
    ingredient = models.CharField(
        "Наименование",
        max_length=200,
    )
    amount = models.CharField(
        "Количество",
        max_length=10,
        blank=True,
    )
    measurement_unit = models.CharField(
        "Единица измерения",
        max_length=10,
        blank=True,
    )

    class Meta:
        verbose_name = "ингредиент"
        verbose_name_plural = "ингредиенты"

    def __str__(self):
        return self.ingredient


class Promocode(models.Model):
    code = models.CharField("Код", max_length=20, unique=True)
    valid_from = models.DateField("Действует с")
    valid_to = models.DateField("Действует до")
    discount = models.IntegerField("Размер скидки, руб")

    class Meta:
        verbose_name = "Промокод"
        verbose_name_plural = "Промокоды"

    def __str__(self):
        return self.code

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, forms
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    username = forms.CharField(
        label='Логин', max_length=75, required=True,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Укажите имя пользователя'
        })
    )
    password = forms.CharField(
        label='Пароль', max_length=75, required=True,
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'Введите пароль'
        })
    )


class RegistrationForm(UserCreationForm):
    username = forms.CharField(
        label='Имя', 
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    email = forms.CharField(
        label='Email',
        widget=forms.EmailInput(attrs={'class': 'form-control'})
    )
    password1 = forms.CharField(
        label='Пароль',
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )
    password2 = forms.CharField(
        label='Подтверждение пароля',
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )    

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

accounts/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView

from .forms import LoginForm, RegistrationForm
from foodplanapp.models import Dish, Order


class LoginUser(auth_views.LoginView):
    def get(self, request, *args, **kwargs):
        form = LoginForm()
        return render(request, "accounts/auth.html", context={"form": form})

    def post(self, request):
        form = LoginForm(request.POST)

        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]

            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("profile")
            return redirect("login")


class LogoutUser(auth_views.LogoutView):
    next_page = reverse_lazy("start_page")


class UserCreateView(CreateView):
    form_class = RegistrationForm
    template_name = "accounts/registration.html"

    def __init__(self):
        self.object = None

    def get_success_url(self):
        return reverse_lazy("login")

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect("profile")


@login_required
def user_profile(request):
    order = (
        Order.objects.prefetch_related("allergies")
        .filter(user__id=request.user.id)
        .first()
    )

    if order and order.payments.filter(is_paid=True).exists():
        allergies = list(
            order.allergies.values(
                "name",
            )
        )

        return render(
            request,
            "accounts/lk.html",
            context={
                "user": request.user,
                "order": order,
                "allergies": allergies,
            },
        )
    else:
        return render(
            request,
            "accounts/lk.html",
            context={
                "user": request.user,
            },
        )


@login_required
def show_receipt(request):
    dish_allergies = []
    dish_items = []

    if request.method == "GET":
        order = Order.objects.prefetch_related("allergies").filter(
            user__id=request.user.id
        )

        allergies = list(order.values_list("allergies", flat=True))

        if any(allergies):
            dish = (
                Dish.objects.prefetch_related("allergies")
                .prefetch_related("dishitems")
                .filter(menu_type=order[0].menu_type, active=True)
                .exclude(allergies__in=allergies)
                .order_by("?")
                .first()
            )

            if dish:
                dish_allergies = list(
                    dish.allergies.values(
                        "name",
                    )
                )
        else:
            dish = (
                Dish.objects.filter(menu_type=order[0].menu_type, active=True)
                .prefetch_related("dishitems")
                .order_by("?")
                .first()
            )

        if dish:
            dish_items = list(
                dish.dishitems.values(
                    "ingredient",
                    "amount",
                    "measurement_unit",
                )
            )

        return render(
            request,
            "accounts/receipt.html",
            context={
                "dish": dish,
                "allergies": dish_allergies,
                "dish_items": dish_items,
            },
        )

accounts/templates/accounts/auth.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Foodplan 2021 - Меню на неделю FOODPLAN</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-light fixed-top navbar__opacity">
            <div class="container">
                <a class="navbar-brand" href="{% url 'start_page' %}">
                    <img src="{% static 'img/logo.8d8f24edbb5f.svg' %}" height="55" width="189" alt="">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse1"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse1">
                    <ul class="navbar-nav w-100">
                        <li class="nav-item nav-item__border">
                            <a class="nav-link active" aria-current="page" href="#">Виды меню</a>
                        </li>
                        <li class="nav-item nav-item__border">
                            <a class="nav-link active" aria-current="page" href="#">Отзывы</a>
                        </li>
                        <li class="nav-item nav-item__border">
                            <a class="nav-link active" aria-current="page" href="#">FAQ</a>
                        </li>
                        <li class="nav-item nav-item__border">
                            <a class="nav-link active" aria-current="page" href="#">Контакты</a>
                        </li>
                        <li class="nav-item align-items-center d-md-flex flex-grow-1 justify-content-end">
                            <button class="btn btn-outline-success me-2 foodplan_green foodplan__border_green">Подписка</button>
                            <button class="btn btn-outline-success foodplan_green foodplan__border_green">Войти</button>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main style="margin-top: calc(2rem + 85px);">
      <div class="container">
        <section>
            <div class="container">
                <div class="card px-5 py-3 d-flex align-items-center foodplan__shadow">
                    <form method="post">
                        {% csrf_token %}
                        <h1 class="mb-4 text-center"><strong>Авторизация</strong></h1>
                          {% for f in form %}
                            <div class="mb-3">
                              <label for="{{ f.id_for_label }}" class="form-label">{{f.label}}</label>{{ f }}
                              <div class="form-error">{{ f.errors }}</div>
                            </div>                          
                          {% endfor %}
                        <div class="row mb-3">
                            <div class="col-12 col-sm-6 mt-3">
                                <button type="submit" class="btn w-100 btn-outline-success foodplan_green foodplan__border_green">Войти</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </section>
      <div class="container">
    </main>
    <footer>
        <nav class="navbar navbar-expand-md navbar-light mt-5">
            <div class="container p-2">
                <a class="navbar-brand" href="#">
                    <img src="{% static 'img/logo.8d8f24edbb5f.svg' %}" height="55" width="189" alt="">
                </a>
                <div class="footer__sideBtns d-flex">
                    <a href="#">
                        <img src="{% static 'img/vk.png' %}" height="38" width="auto" alt="">
                    </a>
                </div>
            </div>
        </nav>
    </footer>
    <footer class="footer pt-2" style="border-top: 1px solid lightgray;">
        <div class="container d-flex flex-row justify-content-center mb-2">
            <small class="text-center">
                <h6>© Девман2022. Все права защищены. © Devman2022. All right reserved.</h6><a href="#"
                    class="link-secondary">Политика конфиденциальности</a>
            </small>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>

</html>

accounts/templates/accounts/lk.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'style.css' %}">
  <title>Foodplan 2022 - Меню на неделю FOODPLAN</title>
</head>
<body>
  <header>
    <nav class="navbar navbar-expand-md navbar-light fixed-top navbar__opacity">
      <div class="container">
        <a class="navbar-brand" href="{% url 'start_page' %}">
          <img src="{% static 'img/logo.8d8f24edbb5f.svg' %}" height="55" width="189" alt="">
        </a>
        <a class="btn btn-outline-success foodplan_green foodplan__border_green" href="{% url 'logout'%}">Выйти</a>
      </div>
    </nav>
  </header>
  <main style="margin-top: calc(2rem + 85px);">
    <section>
      <div class="container">
        <div class="row">
          <div class="card col-12 p-3 mb-5 foodplan__shadow">
            <h4 class="foodplan__backButton">
              <strong><small><a href="#" class="link-secondary fw-light"></a></small></strong>
            </h4>
            <h2 class="text-center"><strong>Личный кабинет</strong></h2>
          </div>

          <div class="card col-12 col-md-2 p-3 mb-3 d-flex flex-column align-items-center foodplan__shadow">
            <div class="position-relative">
              <img src="{% static 'img/test_avatar.png' %}" alt="" width="100" height="100" class="rounded-pill">
              <span class="badge rounded-circle position-absolute bottom-0 end-0 foodplan__bg_green avatar__plus"><a href="#"
                  class="link-dark text-decoration-none align-middle">+</a></span>
            </div>
            <h3 class="card-title text-center">{{ user.username }}</h3>
              <a class="btn btn-outline-success foodplan_green foodplan__border_green" id="logout" href="{% url 'logout'%}">
                Выйти
              </a>
          </div>

          <div class="card col-12 col-md-10 p-3 mb-3 foodplan__shadow">
              <ul class="nav nav-tabs">
                <li class="nav-item foodplan__tab-item">
                  <button id="tab1" class="btn shadow-none foodplan__tab-button active" data-bs-toggle="tab" data-bs-target="#data">Персональные данные</button>
                </li>
                <li class="nav-item foodplan__tab-item">
                  <button id="tab2" class="btn shadow-none foodplan__tab-button" data-bs-toggle="tab" data-bs-target="#menu">Моё меню</button>
                </li>
                <li class="nav-item foodplan__tab-item flex-grow-1"></li>
              </ul>
              <div class="tab-content mt-2">
                <div class="tab-pane fade show active" id="data">
                  <form action="">
                    <div class="mb-3">
                      <div class="d-flex align-items-center justify-content-between">
                        <label for="exampleInputEmail1" class="form-label">Имя</label>
                      </div>
                      <input type="text" class="form-control" id="first_name" value="{{ user.first_name }}">
                    </div>
                    <div class="mb-3">
                      <div class="d-flex align-items-center justify-content-between">
                        <label for="exampleInputEmail1" class="form-label">Фамилия</label>
                      </div>
                      <input type="text" class="form-control" id="last_name" value="{{ user.last_name }}">
                    </div>
                    <div class="mb-3">
                      <label for="exampleInputEmail1" class="form-label">Email</label>
                      <input type="email" class="form-control" id="email" aria-describedby="emailHelp" value="{{ user.email }}">
                    </div>
                  </form>
                </div>
                <div class="tab-pane fade" id="menu">
                  <div class="row">
                    <div class="col-2">
                      <img src="{% static 'img/circle1.png' %}" alt="" class="w-100">
                    </div>
                    <div class="col-10 col-md-10">
                      <div class="row">
                        <div class="col-12">
                          <h2>Подписка</h2>
                        </div>
                        {% if order %}
                        <div class="col-md-12 col-lg-7">
                          <h6>В данной подписке выбраны следующие виды меню:<br>
                              {% if order.breakfast %} Завтраки<br> {% endif %}
                              {% if order.lunch %} Обеды<br> {% endif %}
                              {% if order.dinner %} Ужины<br> {% endif %}
                              {% if order.dessert %} Десерты<br> {% endif %}
                              {% if order.new_year_menu %} Новогоднее меню<br> {% endif %}
                          </h6>
                          <a class="btn btn-outline-success foodplan_green foodplan__border_green" href="{% url 'show_receipt'%}">
                            Показать блюдо
                          </a>
                        </div>
                        <div class="col-md-12 col-lg-5 text-muted d-flex flex-column justify-content-between">
                          <div class="d-flex flex-row justify-content-between">
                            <small>Тип меню: </small><small>{{ order.get_menu_type_display }}</small>
                          </div>
                          <div class="d-flex flex-row justify-content-between">
                            <small>Персоны: </small><small>{{ order.persons_amount }}</small>
                          </div>
                          {% if allergies %}
                            {% for allergy in allergies %}
                              <div class="d-flex flex-row justify-content-between">
                                <small>Аллергия на: </small><small>{{ allergy.name }} </small>
                              </div>
                            {% endfor %}
                          {% else %}
                            <div class="d-flex flex-row justify-content-between">
                              <small>Аллергия на: </small><small>нет </small>
                            </div>
                          {% endif %}
                          <div class="d-flex flex-row justify-content-between">
                            <small>Срок подписки: </small><small>{{ order.duration }} мес</small>
                          </div>
                          {% else %}
                            <div class="col-md-12 col-lg-9">
                              <a class="btn btn-outline-success foodplan_green foodplan__border_green" href="{% url 'order'%}">
                                Оформить подписку
                              </a>
                            </div>
                          {% endif %}
                        </div>

                      </div>
                    </div>
                  </div>
                </div>
              </div>

          </div>
        </div>
      </div>
    </section>
  </main>
  <footer>
    <nav class="navbar navbar-expand-md navbar-light mt-5">
      <div class="container p-2">
        <a class="navbar-brand" href="#">
          <img src="{% static 'img/logo.8d8f24edbb5f.svg' %}" height="55" width="189" alt="">
        </a>
        <div class="footer__sideBtns d-flex">
          <a href="#">
            <img src="{% static 'img/vk.png' %}" height="38" width="auto" alt="">
          </a>
        </div>
      </div>
    </nav>
  </footer>
  <footer class="footer pt-2" style="border-top: 1px solid lightgray;">
    <div class="container d-flex flex-row justify-content-center mb-2">
      <small class="text-center">
        <h6>© Девман2022. Все права защищены. © Devman2022. All right reserved.</h6><a href="#"
          class="link-secondary">Политика конфиденциальности</a>
      </small>
    </div>
  </footer>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>
</body>

accounts/templates/accounts/receipt.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'style.css' %}">
  <title>Foodplan 2022 - Меню на неделю FOODPLAN</title>
</head>
<body>
  <header>
    <nav class="navbar navbar-expand-md navbar-light fixed-top navbar__opacity">
      <div class="container">
        <a class="navbar-brand" href="{% url 'start_page' %}">
          <img src="{% static 'img/logo.8d8f24edbb5f.svg' %}" height="55" width="189" alt="">
        </a>
        <a class="btn btn-outline-success foodplan_green foodplan__border_green" href="{% url 'logout'%}">Выйти</a>
      </div>
    </nav>
  </header>
  <main style="margin-top: calc(2rem + 85px);">
    <section>
      <div class="container">
        <div class="row">
          <div class="card col-12 p-3 mb-5 foodplan__shadow">
            <h4 class="foodplan__backButton">
              <strong><small><a href="#" class="link-secondary fw-light"></a></small></strong>
            </h4>
            <h2 class="text-center"><strong>Рецепт
             {% if dish %}
               {{ dish.name }}
             {% else %}
               не найден
             {% endif %}</strong></h2>
          </div>

          <div class="card col-12 col-md-2 p-3 mb-3 d-flex flex-column align-items-center foodplan__shadow">
            <div class="position-relative">
              <img src="{% static 'img/test_avatar.png' %}" alt="" width="100" height="100" class="rounded-pill">
              <span class="badge rounded-circle position-absolute bottom-0 end-0 foodplan__bg_green avatar__plus"><a href="#"
                  class="link-dark text-decoration-none align-middle">+</a></span>
            </div>
            <h3 class="card-title text-center">{{ user.username }}</h3>
              <a class="btn btn-outline-success foodplan_green foodplan__border_green" id="logout" href="{% url 'logout'%}">
                Выйти
              </a>
          </div>
          {% if dish %}
          <div class="card col-12 col-md-10 p-3 mb-3 foodplan__shadow">
              <div class="tab-content mt-2">
                <div class="tab-pane fade show active" id="data">
                    <div class="mb-3">
                      <b>Фото блюда:</b><br>
                      <img src="{{ dish.image.url }}" height=50% width=50% alt="">
                    </div>
                    <div class="mb-3">
                      <b>Калорийность:</b> {{ dish.calories }} ккал
                    </div>
                    <div class="mb-3">
                      <b>Вес продукта:</b> {{ dish.weight }} г
                    </div>
                    <div class="mb-3">
                      <b>Инструкция по приготовлению:</b> {{ dish.guide }}
                    </div>
                    <div class="mb-3">
                      <b>Ингредиенты:</b>
                      <table style="width: 50%">
                        {% for dish_item in dish_items %}
                          <tr>
                            <td>{{ dish_item.ingredient }}</td>
                            <td>{{ dish_item.amount }} {{ dish_item.measurement_unit }}</td>
                          </tr>
                        {% endfor %}
                      </table>
                    </div>
                    <div class="mb-3">
                      <b>Наличие аллергии в блюде:</b><br>
                       {% if allergies %}
                         {% for allergy in allergies %}
                           {{ allergy.name }}<br>
                         {% endfor %}
                       {% else %}
                          отсутствуют
                       {% endif %}
                    </div>
                    <div class="mb-3">
                      <a class="btn btn-outline-success foodplan_green foodplan__border_green"onClick="window.location.reload()">Новый рецепт</a>
                    </div>
                </div>

              </div>
          </div>
          {% endif %}
        </div>
      </div>
    </section>
  </main>
  <footer>
    <nav class="navbar navbar-expand-md navbar-light mt-5">
      <div class="container p-2">
        <a class="navbar-brand" href="#">
          <img src="{% static 'img/logo.8d8f24edbb5f.svg' %}" height="55" width="189" alt="">
        </a>
        <div class="footer__sideBtns d-flex">
          <a href="#">
            <img src="{% static 'img/vk.png' %}" height="38" width="auto" alt="">
          </a>
        </div>
      </div>
    </nav>
  </footer>
  <footer class="footer pt-2" style="border-top: 1px solid lightgray;">
    <div class="container d-flex flex-row justify-content-center mb-2">
      <small class="text-center">
        <h6>© Девман2022. Все права защищены. © Devman2022. All right reserved.</h6><a href="#"
          class="link-secondary">Политика конфиденциальности</a>
      </small>
    </div>
  </footer>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>
</body>